export const states = ['NOT_STARTED','FACTS_REQUIRED','CUSTOMER_ACTION_REQUIRED','ELIGIBILITY_CHECK','READY','CUSTOMER_AUTHORIZATION_REQUIRED','SUBMISSION_PENDING','FILED','ACCEPTED','REJECTED','RECONCILIATION_REQUIRED','BLOCKED','EXCEPTION','SPECIALIST_INPUT_REQUIRED','COMPLETE'] as const;
export type WorkflowState=typeof states[number];
export type ModuleDefinition={id:string;name:string;description:string;initial:WorkflowState;depends:string[];next:string;source:string;rule:string};
export const modules:ModuleDefinition[]=[
{id:'architecture',name:'Entity architecture',description:'Trading entity and management company connected through documented ownership, authority and operating dependencies.',initial:'FACTS_REQUIRED',depends:[],next:'Confirm residence and operating jurisdiction',source:'Customer facts; jurisdiction records',rule:'FACTS-01'},
{id:'trading',name:'Trading entity',description:'Entity facts, names, customer authorization, external submission and accepted formation record.',initial:'FACTS_REQUIRED',depends:['architecture'],next:'Provide proposed entity name after jurisdiction is confirmed',source:'Customer authorization; state receipt',rule:'ENTITY-01'},
{id:'management',name:'Management company',description:'Management-company relationships, elections and compensation dependencies remain explicit.',initial:'NOT_STARTED',depends:['architecture'],next:'Define management-company operating facts',source:'Customer facts; external filing record',rule:'ENTITY-02'},
{id:'tts',name:'TTS evidence',description:'Activity, time, regularity and continuity evidence; collection is separate from any tax-status conclusion.',initial:'CUSTOMER_ACTION_REQUIRED',depends:[],next:'Start an activity evidence record',source:'https://www.irs.gov/taxtopics/tc429',rule:'EVIDENCE-01'},
{id:'475',name:'Section 475',description:'Election scope, timing, eligibility, authorization and filing evidence are separate states.',initial:'FACTS_REQUIRED',depends:[],next:'Record existing election status; uncertain cases enter an exception',source:'https://www.irs.gov/taxtopics/tc429',rule:'ELECTION-01'},
{id:'ownership',name:'Ownership & UBO',description:'Purpose-limited beneficial ownership and control records with evidence and version history.',initial:'FACTS_REQUIRED',depends:['trading'],next:'Confirm ownership structure when entity facts are ready',source:'Customer ownership record',rule:'OWN-01'},
{id:'kyc',name:'KYC readiness',description:'Institution-specific requests tracked separately from public entity records and government reporting.',initial:'NOT_STARTED',depends:['ownership'],next:'Record the requesting institution and required items',source:'Institution request',rule:'KYC-01'},
{id:'payroll',name:'Payroll',description:'Activation depends on management-company state, employer setup and authorized provider confirmation.',initial:'BLOCKED',depends:['management'],next:'Resolve management-company dependency',source:'Employer record; payroll provider',rule:'PAYROLL-01'},
{id:'benefits',name:'Benefits',description:'Benefit records and applicable prerequisites without automatic eligibility claims.',initial:'BLOCKED',depends:['payroll'],next:'Resolve payroll dependency',source:'Plan and provider records',rule:'BENEFITS-01'},
{id:'accountable',name:'Accountable plan',description:'Business-purpose records, authorizations, receipts and reimbursement evidence.',initial:'NOT_STARTED',depends:['management'],next:'Record business-purpose and reimbursement policy',source:'Customer-approved policy; evidence',rule:'RECORDS-01'},
{id:'filings',name:'Filing reconciliation',description:'Submission is distinct from acceptance. External receipts and status are preserved.',initial:'NOT_STARTED',depends:['trading'],next:'Attach external filing reference after authorized submission',source:'Government or authorized provider receipt',rule:'RECON-01'},
{id:'obligations',name:'Annual obligations',description:'Due dates derive from actual jurisdiction, accepted records and source versions.',initial:'FACTS_REQUIRED',depends:['trading'],next:'Establish jurisdiction before generating statutory deadlines',source:'Accepted formation and jurisdiction source',rule:'OBLIGATION-01'},
];
const transitions:Record<WorkflowState,WorkflowState[]>={NOT_STARTED:['FACTS_REQUIRED','BLOCKED'],FACTS_REQUIRED:['ELIGIBILITY_CHECK','CUSTOMER_ACTION_REQUIRED'],CUSTOMER_ACTION_REQUIRED:['ELIGIBILITY_CHECK','READY'],ELIGIBILITY_CHECK:['READY','BLOCKED','SPECIALIST_INPUT_REQUIRED','EXCEPTION'],READY:['CUSTOMER_AUTHORIZATION_REQUIRED','COMPLETE','FACTS_REQUIRED'],CUSTOMER_AUTHORIZATION_REQUIRED:['SUBMISSION_PENDING','FACTS_REQUIRED'],SUBMISSION_PENDING:['FILED','EXCEPTION'],FILED:['ACCEPTED','REJECTED','RECONCILIATION_REQUIRED'],ACCEPTED:['COMPLETE','RECONCILIATION_REQUIRED'],REJECTED:['FACTS_REQUIRED','SPECIALIST_INPUT_REQUIRED'],RECONCILIATION_REQUIRED:['ACCEPTED','EXCEPTION'],BLOCKED:['FACTS_REQUIRED','READY'],EXCEPTION:['FACTS_REQUIRED','SPECIALIST_INPUT_REQUIRED'],SPECIALIST_INPUT_REQUIRED:['ELIGIBILITY_CHECK','FACTS_REQUIRED'],COMPLETE:['RECONCILIATION_REQUIRED','FACTS_REQUIRED']};
export function canTransition(from:WorkflowState,to:WorkflowState){return transitions[from]?.includes(to) || false;}
export function validateTransition(from:WorkflowState,to:WorkflowState,actor:'customer'|'system'|'operator',authority?:string){
 if(!canTransition(from,to))throw new Error('Invalid workflow transition');
 if(['SUBMISSION_PENDING','FILED','ACCEPTED','COMPLETE'].includes(to) && !authority)throw new Error('Evidence or authorization is required');
 if(actor==='customer' && ['FILED','ACCEPTED','COMPLETE','READY'].includes(to))throw new Error('Customer cannot assert external effectiveness');
}
export const sampleStates:Record<string,WorkflowState>={architecture:'READY',trading:'ACCEPTED',management:'SPECIALIST_INPUT_REQUIRED',tts:'CUSTOMER_ACTION_REQUIRED','475':'FACTS_REQUIRED',ownership:'READY',kyc:'CUSTOMER_ACTION_REQUIRED',payroll:'BLOCKED',benefits:'BLOCKED',accountable:'NOT_STARTED',filings:'RECONCILIATION_REQUIRED',obligations:'CUSTOMER_ACTION_REQUIRED'};
export const displayState=(s:string)=>s.replaceAll('_',' ');
