'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {modules,sampleStates,displayState} from '@/lib/workflows';
import {commercial,money} from '@/lib/config';
import {Activate} from './chrome';
import {track} from './telemetry';
type RecordRow={id:string;module?:string;state?:string;version?:number;source?:string;rule_version?:string;kind?:string;created_at?:string;new_state?:string;previous_state?:string;actor?:string;label?:string;reference?:string;title?:string;due_at?:string;status?:string};
type DeskData={desk:{os_reference:string;status:string;activated_at:string;renews_at:string;renewal_status:string;cancel_at_period_end:boolean};workflows:RecordRow[];history:RecordRow[];evidence:RecordRow[];obligations:RecordRow[]};
const tabs=['Overview','Entities','Evidence & elections','Ownership & KYC','Payroll & benefits','Obligations','Documents','Audit history','Membership'];
const sampleHistory=[{id:'sample-1',kind:'Customer facts recorded',source:'Facts snapshot F-003 · customer declaration',new_state:'ELIGIBILITY_CHECK',created_at:'2026-09-03T09:14:00Z',actor:'customer'},{id:'sample-2',kind:'Customer authorization recorded',source:'Authorization A-018 · exact document v2',new_state:'SUBMISSION_PENDING',created_at:'2026-09-03T10:02:00Z',actor:'customer'},{id:'sample-3',kind:'Trading-entity acceptance reconciled',source:'Fictitious external receipt R-018',new_state:'ACCEPTED',created_at:'2026-09-03T11:42:00Z',actor:'system'},{id:'sample-4',kind:'Management-company exception recorded',source:'Compensation dependency · specialist input required',new_state:'SPECIALIST_INPUT_REQUIRED',created_at:'2026-09-03T11:58:00Z',actor:'system'},{id:'sample-5',kind:'Annual obligation scheduled',source:'Fictitious accepted formation · anniversary source',new_state:'CUSTOMER_ACTION_REQUIRED',created_at:'2026-09-03T13:45:00Z',actor:'system'}];
export default function Desk({sample=false}:{sample?:boolean}){const [tab,setTab]=useState('Overview'),[selected,setSelected]=useState<string|null>(null),[data,setData]=useState<DeskData|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch('/api/desk');const b=await r.json();if(!r.ok){setError(b.error);return;}setData(b);setError('');}catch{setError('Your Desk could not load. Refresh safely or sign in again.');}}
 useEffect(()=>{if(!sample){fetch('/api/desk').then(async r=>{const b=await r.json();if(!r.ok)setError(b.error);else setData(b);}).catch(()=>setError('Connection interrupted. Refresh safely.'));}},[sample]);
 if(!sample && error)return <div className="narrow"><h1>Your private Desk</h1><p role="alert">{error}</p><Link className="button primary" href="/account">SIGN IN</Link><p className="small">A Desk reference alone grants no access.</p></div>;
 if(!sample && !data)return <p className="loading" role="status">Loading your authenticated operating record…</p>;
 const state=(id:string)=>sample?sampleStates[id]:data?.workflows.find(w=>w.module===id)?.state||'NOT_STARTED';
 const version=(id:string)=>sample?3:data?.workflows.find(w=>w.module===id)?.version||1;
 const visible=modules.filter(m=>tab==='Overview'||tab==='Entities'&&['architecture','trading','management','accountable','filings'].includes(m.id)||tab==='Evidence & elections'&&['tts','475'].includes(m.id)||tab==='Ownership & KYC'&&['ownership','kyc'].includes(m.id)||tab==='Payroll & benefits'&&['payroll','benefits'].includes(m.id));
 const active=modules.find(m=>m.id===selected);
 async function billing(action:'billing'|'cancel'|'referral'|'logout'){setBusy(true);setMessage('');try{const r=await fetch(`/api/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Request could not complete.');if(b.url && action!=='referral')window.location.assign(b.url);else{setMessage(b.message||b.url);await refresh();}}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 return <div className="shell"><div className="deskheading"><div><p className="eyebrow">{sample?'SAMPLE DATA / FICTITIOUS PRODUCT DEMONSTRATION':'AUTHENTICATED / PRIVATE OPERATING FILE'}</p><h1>{sample?'Pro Alpha OS · Sample Trader 001':'Your Pro Alpha OS'}</h1><p>Every fact, document, authorization, external state and next action belongs to one reconstructable operating record.</p></div>{sample?<Activate/>:<button className="button secondary" onClick={()=>billing('logout')}>SIGN OUT</button>}</div><div className="deskmeta"><div><span>OS REFERENCE</span><strong>{sample?'PA-SAMPLE001':data?.desk.os_reference}</strong></div><div><span>OS MEMBERSHIP</span><strong className="gold">{sample?'ACTIVE · SAMPLE':data?.desk.status}</strong></div><div><span>ARCHITECTURE</span><strong>Trading entity + management company</strong></div><div><span>RULE VERSION</span><strong>{commercial.version}</strong></div></div><div className="notice">{sample?'SAMPLE DATA ONLY. The example trading entity is accepted; the management company requires specialist input. Payroll stays blocked by that dependency.':'Your OS is active independently of your entity, election, filing, payroll or benefit states. Next required action: confirm operating jurisdiction.'}</div><div className="deskgrid"><aside className="deskmenu" aria-label="Desk modules"><p className="eyebrow">OPERATING FILE</p>{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setSelected(null);}}>{t}</button>)}</aside><div className="deskcontent">
 {active?<div className="detailpane"><button className="backbutton" onClick={()=>setSelected(null)}>← Back to {tab}</button><div><span className="pill">{displayState(state(active.id))}</span><h2>{active.name}</h2><p>{active.description}</p><div className="nextcard"><span className="eyebrow">NEXT REQUIRED ACTION</span><strong>{active.next}</strong></div><div className="detailmeta"><div><span>DEPENDENCIES</span><strong>{active.depends.map(d=>`${modules.find(m=>m.id===d)?.name}: ${displayState(state(d))}`).join(' · ')||'Independent workflow'}</strong></div><div><span>SOURCE PROVENANCE</span><strong>{active.source}</strong></div><div><span>RULE VERSION</span><strong>{commercial.version} / {active.rule}</strong></div><div><span>OBJECT VERSION</span><strong>v{version(active.id)}</strong></div><div><span>ACTOR / AUTHORITY</span><strong>{sample?'SAMPLE: customer declaration or fictitious external receipt':'Customer facts; explicit authorization; externally evidenced effectiveness'}</strong></div><div><span>EXTERNAL EFFECTIVENESS</span><strong>{state(active.id)==='ACCEPTED'?'Accepted record shown in sample':'No accepted external state asserted'}</strong></div></div>{!sample && ['architecture','475','tts'].includes(active.id)&&['FACTS_REQUIRED','CUSTOMER_ACTION_REQUIRED','ELIGIBILITY_CHECK','SPECIALIST_INPUT_REQUIRED'].includes(state(active.id))?<FactForm module={active.id} onComplete={refresh}/>:<p className="small">{sample?'Sample records are isolated from customer data. Activate your membership to create your own operating file.':'This workflow requires its displayed dependency or evidence before it can advance. No external filing has been performed.'}</p>}</div></div>:
 ['Obligations','Documents','Audit history','Membership'].includes(tab)?<>
 <h2>{tab}</h2>{!sample && tab==='Documents' && <Link className="button secondary" href="/api/export" prefetch={false}>EXPORT OPERATING RECORD</Link>}{tab==='Audit history'?<div className="timeline">{(sample?sampleHistory:data?.history||[]).map(h=><article key={h.id}><span className="mono">{h.created_at?.slice(0,16).replace('T',' ')} · {h.actor}</span><h3>{h.kind}</h3><p>{h.source}</p><span className="pill">{displayState(h.new_state||'RECORDED')}</span></article>)}</div>:tab==='Documents'?<div className="records">{(sample?[{id:'e1',label:'Trading-entity certified record',reference:'SAMPLE / R-018 / v2',source:'Fictitious state-channel receipt'},{id:'e2',label:'Customer authorization',reference:'SAMPLE / A-018 / v2',source:'Fictitious customer selection'},{id:'e3',label:'TTS activity evidence',reference:'SAMPLE / F-003 / v8',source:'Fictitious activity record'}]:data?.evidence||[]).map(e=><article key={e.id}><h3>{e.label}</h3><p>{e.reference}</p><p>Source: {e.source}</p></article>)}{!sample && !data?.evidence.length&&<p>No evidence recorded yet. Submit the next requested fact to begin your evidence history.</p>}</div>:tab==='Obligations'?<div className="records">{(sample?[{id:'o1',title:'Annual report',status:'MONITORING',source:'SAMPLE accepted formation · anniversary month',due_at:'2027-05-24'},{id:'o2',title:'Election workflow timing',status:'FACTS_REQUIRED',source:'SAMPLE tax workflow · eligibility and timing unresolved'},{id:'o3',title:'Continuing OS Membership',status:'SCHEDULED',source:'SAMPLE membership activation',due_at:'2027-09-03'}]:data?.obligations||[]).map(o=><article key={o.id}><h3>{o.title}</h3><span className="pill">{displayState(o.status||'FACTS_REQUIRED')}</span><p>Due: {o.due_at?.slice(0,10)||'Pending applicable facts'}</p><p>Source: {o.source}</p></article>)}</div>:<div className="detailpane"><p className="eyebrow">CONTINUING OS MEMBERSHIP</p><h2>{money(commercial.renewalCents)}/year</h2><p>Includes Desk access, operating record, workflows, evidence, recurring obligations and history.</p><p>Renewal date: {sample?'2027-09-03 · SAMPLE':data?.desk.renews_at?.slice(0,10)}</p><p>Status: {sample?'SCHEDULED · SAMPLE':data?.desk.renewal_status}</p>{!sample&&<><div className="billingactions"><button className="button secondary" disabled={busy} onClick={()=>billing('billing')}>MANAGE BILLING</button>{!data?.desk.cancel_at_period_end&&<button className="button danger" disabled={busy} onClick={()=>setMessage('confirm-cancel')}>CANCEL RENEWAL</button>}<button className="button secondary" onClick={()=>billing('referral')}>CREATE REFERRAL LINK</button></div>{message==='confirm-cancel'?<div className="notice"><p>Cancel the next annual renewal? Access continues through your paid membership period.</p><button className="button danger" disabled={busy} onClick={()=>billing('cancel')}>CONFIRM CANCELLATION</button><button className="backbutton" onClick={()=>setMessage('')}>Keep membership</button></div>:<p role="status">{message}</p>}</>}</div>}
 </>:<><h2>{tab==='Overview'?'Controlled operating state':tab}</h2><p className="small">Select a module to inspect dependencies, next action, source and version.</p><div className="workflowcards">{visible.map(m=><button className="workflowcard" key={m.id} onClick={()=>{setSelected(m.id);if(!sample)track('customer_item_requested');}}><div className="workflowtop"><span className="mono">v{version(m.id)} / {m.rule}</span><span className="pill">{displayState(state(m.id))}</span></div><h3>{m.name}</h3><p>Next: {m.next}</p></button>)}</div></>}
 </div></div></div>}
function FactForm({module,onComplete}:{module:string;onComplete:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(''),[requestKey]=useState(()=>crypto.randomUUID());async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const value=module==='architecture'?{state:form.get('state'),existingEntity:form.get('existingEntity')}:module==='475'?{election:form.get('election')}:{date:form.get('date'),minutes:Number(form.get('minutes')),activity:form.get('activity')};try{const r=await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module,requestKey,value})});const b=await r.json();if(!r.ok)throw new Error(b.error);setDone('Facts recorded. Your workflow state and evidence history have been updated.');await onComplete();}catch(e){setError(e instanceof Error?e.message:'Connection interrupted. Retry safely.');}finally{setBusy(false);}}
 return <form onSubmit={submit}><h3>Provide the next required fact</h3><p className="small">{module==='architecture'?'Your residence/operating state is required to establish jurisdiction dependencies. You may defer by leaving this screen.':module==='475'?'Existing election status is required before election timing or applicability can be evaluated. “Not sure” creates an explicit specialist exception.':'Your dated activity record builds evidence; recording it does not determine Trader Tax Status.'}</p>{module==='architecture'?<><label htmlFor="state">Operating state</label><select id="state" name="state" required><option value="">Select state</option>{['AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'].map(s=><option key={s}>{s}</option>)}</select><label htmlFor="existingEntity">Existing entity?</label><select id="existingEntity" name="existingEntity" required><option value="no">No</option><option value="yes">Yes</option><option value="unsure">Not sure</option></select></>:module==='475'?<><label htmlFor="election">Existing §475 election</label><select id="election" name="election"><option value="unsure">Not sure</option><option value="not_filed">Not filed</option><option value="filed">Filed — evidence still required</option></select></>:<><label htmlFor="date">Activity date</label><input id="date" name="date" type="date" required/><label htmlFor="minutes">Minutes devoted</label><input id="minutes" name="minutes" type="number" min="1" max="1440" required/><label htmlFor="activity">Activity description — no account numbers or private credentials</label><input id="activity" name="activity" minLength={3} maxLength={300} required/></>}{error&&<p className="error" role="alert">{error}</p>}{done&&<p className="success" role="status">{done}</p>}<button className="button primary" disabled={busy} style={{marginTop:22}}>{busy?'RECORDING…':'RECORD FACTS'}</button></form>}
